batch_size: 256
warm_up: 2
epochs: 100
eval_every_n_epochs: 1
save_every_n_epochs: 1
log_every_n_steps: 10
fp16_precision: False
init_lr: 0.005
weight_decay: 1e-5
gpu: cuda:1
model_type: MolEN
model:
  num_layer: 3
  emb_dim: 300
  feat_dim: 512
  drop_ratio: 0
  pool: mean
aug: mix
dataset:
  num_workers: 18
  valid_size: 0.05
  data_path: ./data/data.txt

loss:
  temperature: 0.05
  use_cosine_similarity: True
